### ISSUE TITLE
The notebook `book_equations` should be updated for HoML2

### ISSUE THREAD

**Issue by paulcarey** [ageron/handson-ml2#104]
Some equations in the Kindle edition are not properly rendered, for example, 16-3 below. It would be very helpful for the `book_equations` notebook to be updated so Kindle readers can view the correct equations. Thanks.

<img width="662" alt="Screenshot 2020-02-10 at 06 18 28" src="https://user-images.githubusercontent.com/9439/74125565-947fbe00-4bcd-11ea-93f2-4299149bad0b.png">

**Comment by ageron** [comment]
Thanks for your feedback, and sorry for the late response, the last few months have been a bit hectic for me. These equation formatting issues on Kindle are really killing me. I've reported them to O'Reilly several times, but they're really hitting serious difficulties with Kindle formatting, reportedly because of the wide variety of kindle formats. I sincerely apologize for the inconvenience. :/

I'll try to update the book_equations notebook asap. Thanks for your patience. I hope you're enjoying the book despite these formatting issues.

**Comment by ageron** [comment]
I just uploaded a PDF containing all the equations in the book. Hope this helps.
