### ISSUE TITLE
Ch 15: Training Size in Epochs are Different

### ISSUE THREAD

**Issue by bschmook** [ageron/handson-ml2#183]
Hi! 

Great book. I am running the examples in Ch 15 to acclimate myself to the frameworks and I noticed that my epoch batch sizes are different than the examples. I am getting 219 versus 7000. I have attached a snip of my code and output. I have it running on GPU (or at least I think I do), not sure if it is some type of setting or computation on my PC. Any insight is appreciated.

Thanks!

![ch15 samps](https://user-images.githubusercontent.com/48573952/84315447-abacc900-ab37-11ea-8d2e-2dfe6525ef0e.JPG)

**Comment by Irempo** [comment]
I have the same issue, I couldn't find why this happens! How did you fix it? 
Thanks in advance for your answer

**Comment by ageron** [comment]
Hi @bschmook ,
Sorry for the late reply, I missed this question. Don't worry, everything is working fine, it's just that since TensorFlow 2.2, TF Keras displays the batch number rather than the instance number. Since the batch size is 32 by default, it means that it will display numbers batch numbers:
1/219, 2/219, 3/219, ..., 218/219, 219/219
instead of
32/7000, 64/7000, 96/7000, ..., 6968/7000, 7000/7000

219 is just 7000/32 (rounded up).

Hope this helps.
