### ISSUE TITLE
Chapter 11 Exercise 8 transfer learning question

### ISSUE THREAD

**Issue by gkd720** [ageron/handson-ml2#19]
I'm unclear on how to generate the digits' 0-4 datasets. In the chapter 11 notebook, I see where the output layer is 8 neurons since it's only trying to output 1 of 8 classes. But, do the "y" values have to be zero-based and contiguous? Looks like "yes" based on the example. For the exercise, I wanted to make a 0-4 dataset, and a 5-9 dataset, leaving the y's equal to 5,6,7,8, or 9. So should they be modified down to 0-4 by subtracting 5? And why, in the exercise, do the generated binary values have to be a float? Wouldn't integer work?

For the splitting function, I wanted to do something like:
```
# Build training data with digits 0-4
def split_dataset(X, y):
    y_56789 = y > 4 # digits 5,6,7,8,9
    y_A = y[~y_56789] # since deleting 5 - 9, no need to modify remaining 0 - 4 class numbers
    y_B = y[y_56789]
    return ((X[~y_56789], y_A),
            (X[y_56789], y_B))
```
Does this work? Thanks.

**Comment by ageron** [comment]
Hi @gkd720 ,

Thanks for your question, and sorry for the late response, I was on vacation.

When you use the `sparse_categorical_crossentropy` loss, Keras expects the targets to be zero-based class indices. Keras is tolerant: it accepts these indices as integers or floats, but since they're supposed to have whole values, I prefer to make it clear and cast them to integers.

So you need to subtract 5 from `y_B` (and of course add 5 to the model's predictions). Otherwise, your code looks good to me.

Hope this help,
Aurélien
