### ISSUE TITLE
Chapter 18 - env.step(1) code leads to error: AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by activationfunction** [ageron/handson-ml2#203]
Thank you for your awesome book. It is my personal bible on ML and AI topics. I have purchased both the first and second editions and plan to purchase all future editions. The book is that great!

I'd be very grateful if you can lend a helping hand on a code error I'm getting on Chapter 18 > Using TF-Agents to Beat Breakout > TF-Agents Environments. The code is:

`env.step(1) # Fire`

The error I get is:

`AttributeError: 'int' object has no attribute 'item'`

Your help on this error would be so greatly appreciated. Thanks in advance.

**Comment by ferrari-leo** [comment]
I tried the following and it worked: 

`env.step(np.array(1))`

This might be because in the source code, the actual action is pulled out of the 'action' object that you should pass to the `step()` method: 

`def _step(self, action):

 ...


    # Some environments (e.g. FrozenLake) use the action as a key to the
    # transition probability so it has to be hashable. In the case of discrete
    # actions we have a numpy scalar (e.g array(2)) which is not hashable
    # in this case, we simply pull out the scalar value which will be hashable.
    action = action.item() if self._action_is_discrete else action

  ...

`

This somehow means you can't input int objects as actions to the `step()` method for the moment...

**Comment by activationfunction** [comment]
Wow, thanks, torlenor!

**Comment by ageron** [comment]
It's heartwarming to read these comments! Thanks everyone. 😊 🙏 
I've been busy on other projects for a while, I apologise for the long inactivity here.

The good news is that TF Agents fixed the issue upstream, so if you update to the latest version of TF Agents, you should be able to use `.step(1)` instead of `.step(np.array(1))`.

Thanks again!

**Comment by activationfunction** [comment]
Very cool to hear from the big boss Dr. Aurélien Geron himself. :)

**Comment by ageron** [comment]
Thanks @activationfunction! Note that I'm not a Doctor. But you can call me big boss, that works for me. 😂

**Comment by activationfunction** [comment]
Whether or not you have a Ph.D., you'll always be the big boss AI doctor in my book. 😆
