### ISSUE TITLE
Chapter 6 – Decision Trees - No module named 'graphviz' when run in my local notebook

### ISSUE THREAD

**Issue by snowtigger** [ageron/handson-ml2#213]
When running the following code on my laptop local notebook, I got `ModuleNotFoundError: No module named 'graphviz'`

```python
from graphviz import Source
from sklearn.tree import export_graphviz

export_graphviz(
        tree_clf,
        out_file=os.path.join(IMAGES_PATH, "iris_tree.dot"),
        feature_names=iris.feature_names[2:],
        class_names=iris.target_names,
        rounded=True,
        filled=True
    )
```

**Comment by JosephChan101** [comment]
I believe graphviz is not compatible with Windows

**Comment by YuriGagarine** [comment]
1) You have to download graphviz here : https://graphviz.org/download/

2) Add to your environment variable PATH : "C:\Program Files (x86)\Graphviz2.38\bin"  (Adapt with your Graphviz path)

3) Now your code should run

**Comment by DocMinus** [comment]
Graphviz for windows can be installed like this (I didn't need to fiddle with PATH).
If you use conda:
`conda install python-graphviz`
alt:
`python -m pip install graphviz`

Actually, under Linux, I had issues with the conda, there I had to use pip.

**Comment by HumayRaphael** [comment]
i have the same problem on mac.

**Comment by ageron** [comment]
Thanks for your feedback @snowtigger , and thanks for the great answers everyone.
The `graphviz` python library relies on the Graphviz software when generating DOT files (used only in chapter 6). So both need to be installed.
When using Anaconda, it's easy: you just need to run `conda install python-graphviz` to get the Python library, and run `conda install graphviz` to get the Graphviz software.
When using `pip` instead of Anaconda, you can install the Python library easily, by running `pip install graphviz`, but you must install the Graphviz software manually (see the **Installation** section on [this page](https://pypi.org/project/graphviz/)).
Hope this helps.

**Comment by JingwenLl** [comment]
I tried to install graphviz as Geron recommended, but it is stuck at solving environment. 

Is there any solution to this? 

Thanks!

**Comment by ageron** [comment]
Hi @JingwenLl ,
Could you please provide some details about your environment? Are you on Windows? Using Anaconda? Perhaps it would help to update conda:

```bash
conda update -c defaults -n base conda
```

Then don't forget to activate the conda environment for this project:

```bash
conda activate tf2
```

Also, you may want to add `-c anaconda` to the `conda install` commands above:

```bash
conda install -c anaconda python-graphviz
conda install -c anaconda graphviz
```

If the system is stuck on "Solving environment: " with a rotating bar (\ - / - \ - /...) then perhaps there is a network issue? Do you have a firewall? Or running a VPN?

**Comment by JingwenLl** [comment]
Hi ageron, 

Thank you for your suggestions. I have resolved the issue by creating a new virtual environment and following your code: 
conda install python-graphviz
conda install graphviz

Thanks!
