### ISSUE TITLE
Chapter 3, Training a Binary Classifier, ValueError: Expected 2D array, got 1D array instead: array=[1]

### ISSUE THREAD

**Issue by wavymatt** [ageron/handson-ml2#215]
Hello, when running the code example in Chapter 3 for Training a Binary Classifier, I am getting the following error.
```
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=1000, tol=1e-3, random_state=42)
sgd_clf.fit(X_train, y_train_5)

sgd_clf.predict([1])
```

```
ValueError: Expected 2D array, got 1D array instead:
array=[1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

**Comment by JosephChan101** [comment]
The input of prediction is incorrect, you need to feed images of digit to the model. In this example, each image is represented as a 784-pixel vector. Since the model can predict many images in one batch, so it expects an input of (batch_size,  784), a two-dimensional array. What you did was just to give the model a 1D vector of 1, you need to reconstruct it to something like this: [[0,0,..0.5, 0.9, 0.75,...,0,0]], notice this is a 2 dimensional array with a shape (1, 784).

Remember that you train the model with X_train, which has a shape of (60000, 784)

You can just pick some digit from X such as:
some_digit = X[0]
then
sgd_clf.predict([some_digit])
If X[0] is an image of 5, it returns True, otherwise it returns False.
Hope this help

**Comment by wavymatt** [comment]
Yes, that works thank you!
