### ISSUE TITLE
Data Visualization - Clustering

### ISSUE THREAD

**Issue by tnmymtr** [ageron/handson-ml2#306]
How can we get the data visualization of the training data the way shown in the book in various figures, especially along with the decision boundaries?

**Comment by Praful932** [comment]
@tnmymtr Could you specify which Chapter? Most of the figures and the code are available in the notebooks.

**Comment by AndreasTraut** [comment]
> How can we get the data visualization of the training data the way shown in the book in various figures, especially along with the decision boundaries?

At the end of the jupyter notebooks, there is sometimes some more helpful material. Also have a look at the "tools_xxx.ipynb" files to learn about matplotlib. Visit also the gallery (https://matplotlib.org/gallery.html) to learn visualization techniques. And if you bought the first version of his book, then you can also have a look at https://github.com/ageron/handson-ml (instead of "handson_ml2"). I hope this helps a bit.

**Comment by ageron** [comment]
Hi @tnmymtr ,
Thanks for your question. As @Praful932 and @AndreasTraut said (thanks!), most figures were generated using Matplotlib, and the code is available in the Jupyter notebooks.
Hope this helps. I'm closing this issue, please reopen if you need more help on this.
