### ISSUE TITLE
CHAPTER 11: 1CYCLE SCHEDUALER

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml2#334]
Hi, 

I have a problem with understanding the ```_interpolate``` function's details. 

```python
def _interpolate(self, iter1, iter2, rate1, rate2):
         return ((rate2 - rate1) * (self.iteration - iter1) / (iter2 - iter1) + rate1)
```

I understand it calculates and controls the shrinkage and growth of the learning rate; what I do not get is the mathematical detail that how it works!
any explanation about its math and also a bit of detail about its surroundings (the related parts of code) will be appreciated.

**Comment by ageron** [comment]
Hi @kasrahabib ,

Suppose the learning rate must be at `rate1` at iteration `iter1`, and it must then change linearly until it reaches `rate2` at iteration `iter2`. If it helps, give these variables some values, for example `rate1=0.1`, `iter1=100`, `rate2=0.5` and `iter2=300`. Since the change is linear, we know that `_interpolate()` will return a value equal to `a * self.iteration + b` (a linear equation). The question is: what's the value of `a` and `b`? Well, we know that `_interpolate()` should return `rate1` when `self.iteration=iter1`, and it should return `rate2` when `self.iteration=iter2`, so:

```
a * iter1 + b = rate1
a * iter2 + b = rate2
```

If you subtract the first equation from the second, you get:

```
(a * iter2 + b) - (a * iter1 + b) = rate2 - rate1
```

which can be simplified to:

```
a * (iter2 - iter1) = rate2 - rate1
```

and therefore:

```
a = (rate2 - rate1) / (iter2 - iter1)
```

Great, we found `a`! Now let's find `b` by looking at the first equation again:

```
a * iter1 + b = rate1
```

We get:

```
b = rate1 - a * iter1
```

So we now have everything we need to define the `_interpolate()` function. As discussed above, it should return `a * self.iteration + b`. Let's start by replacing `b` with `rate1 - a*iter1`:

```
result = a * self.iteration + rate1 - a*iter1
```

Then we factor out `a`:

```
result = a * (self.iteration - iter1) + rate1
```

And lastly, we can replace `a` with the value we calculated above:

```
result = (rate2 - rate1) / (iter2 - iter1) * (self.iteration - iter1) + rate1
```

Which can be rewritten as:

```
result = (rate2 - rate1) * (self.iteration - iter1) / (iter2 - iter1) + rate1
```

Hope this helps.

**Comment by kasrahabib** [comment]
Hi, 

Thanks a lot.
So far I understand everything and it is much clear now.
Just one more thing: Why we subtract the ```equation 2``` from ```equation 1```?

I think I am the only one who asked a lot of questions.😁
I know you might be very busy, so I appreciate your time answering.

Thanks in advance! 😊

**Comment by kasrahabib** [comment]
Hi, 

Thanks a lot.
So far I understand everything and it is much clear now.

Just one more thing: Why we subtract the ```equation 2``` from ```equation 1```?

I think I am the only one who asked a lot of questions.😁
I know you might be very busy, so I appreciate your time answering.

Thanks in advance! 😊

**Comment by kasrahabib** [comment]
Hi,

I know, I am the only one who asks a lot (several issues opened by me) of questions. 😁
The ```_interpolate()``` function is very clear now: just one further thing, why we subtract ```eq1``` from ```eq2```?

I know you are very busy, so I appreciate answering back! ☺️
Thanks in advance!

**Comment by ageron** [comment]
Hi @kasrahabib ,
Since there's one `b` in equation 1, and one `b` in equation 2, if we subtract one equation from the other, it gets rid of `b`. This means we are left with one equation with one unknown variable `a`, and that's easy to solve. More generally, when you have N equations with N unknowns, the trick is to get rid of one variable at a time. Say there are five `b` in one equation, and seven `b` in another equation, you can get rid of `b` by multiplying the first equation by 7 (so there are now 35 `b`) and subtracting the second equation times 5 (so it also has 35 `b`).
If this is unclear, check out this [Khan Academy course](https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:linear-equations-graphs).
Hope this helps.

**Comment by kasrahabib** [comment]
Hi @ageron,

Just kicked in. 
I was completely forgotten about that part of linear algebra. 
we are only doing the math to find ```a``` and ```b```.
I was trying to relate that to something else and much bigger, even did not think about that part.


YOU ARE THE BEST!!!
