### ISSUE TITLE
Chapter 12 Losses and Metrics Based on Model Internals

### ISSUE THREAD

**Issue by nickstegmeier** [ageron/handson-ml2#339]
The following code, copied exactly from the reconstruction loss example in chapter 12, gives an error.

```python
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

import tensorflow as tf
import tensorflow.keras as keras

class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)

    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        self.reconstruct = keras.layers.Dense(n_inputs)
        super().build(batch_input_shape)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        return self.out(Z)
    
model = ReconstructingRegressor(1)
model.compile(loss="mse", optimizer="nadam")
history = model.fit(X_train_scaled, y_train, epochs=2)
y_pred = model.predict(X_test_scaled))
```

The error I receive happens in `model.fit()` and says

> InaccessibleTensorError: The tensor 'Tensor("mul:0", shape=(), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=build_graph, id=140171496905552); accessed from: FuncGraph(name=train_function, id=140171497848592).

**Comment by 2kich** [comment]
Hi @nickstegmeier . 

The general solution is here [#41693](https://github.com/tensorflow/tensorflow/issues/41693) but it doesn't work for me even I put callable to `self.add_loss()`, it works in general if you put just constant. 

I found a more complex [solution](https://github.com/ageron/handson-ml2/issues/159#issuecomment-630323233) that works.

**Comment by lukebor** [comment]
My solution for this problem.

`class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
        self.reconstruct = keras.layers.Dense(input_shape[-1])
        # TODO: check https://github.com/tensorflow/tensorflow/issues/26260
        #self.reconstruction_mean = keras.metrics.Mean(name="reconstruction_error")
   # i didn't see any useful documentation telling about how to use build method in model class, instead of layer class
   # so i moved it to __init__
   # def build(self, batch_input_shape):
   #     n_inputs = batch_input_shape[-1]
   #     self.reconstruct = keras.layers.Dense(n_inputs)
   #     super().build(batch_input_shape)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        #if training:
        #    result = self.reconstruction_mean(recon_loss)
        #    self.add_metric(result)
        return self.out(Z)`

**Comment by lukebor** [comment]
```
class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
        self.reconstruct = keras.layers.Dense(input_shape[-1])

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)

        return self.out(Z)
```

for 0.05 * recon_loss

```
Epoch 1/2
363/363 [==============================] - 2s 2ms/step - loss: 2.0089
Epoch 2/2
363/363 [==============================] - 1s 2ms/step - loss: 0.5085
```

for 10*recon_loss

```
Epoch 1/2
363/363 [==============================] - 2s 1ms/step - loss: 6.7786
Epoch 2/2
363/363 [==============================] - 1s 1ms/step - loss: 4.0873
```

Works Good! 👍 
The reason i removed the Build method is that i didnt find useful information in  TF documentation how to use build in Model Class. Only usable information was for custom layers to initialize weight bias matrix. After moving reconstruct to init it is still waiting for input_shape. Different inputs then different units in Dense layers. Hope this helps

**Comment by 2kich** [comment]
Hi, @lukebor  thank you. What environment do you use, I got an error `NameError: name 'input_shape' is not defined` on `self.reconstruct = keras.layers.Dense(input_shape[-1])` because it's doesn't know what is  `input_shape` at the initialization step `__init__`.

**Comment by lukebor** [comment]
Hi @2kich i just ran it on colab opening from this github. Executing from begining of notebook

**Comment by 2kich** [comment]
I am aware that `**kwargs ` contains, as well as other defaults such as name, etc..  Seems my Colab is [broken](https://colab.research.google.com/drive/1EwosnPiEwucxziWoBXB31DHVH0fnljdB?usp=sharing) :)

**Comment by lukebor** [comment]
```
class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim,input_sh, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
        self.reconstruct = keras.layers.Dense(input_sh[-1])

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        return self.out(Z)
    
model = ReconstructingRegressor(1, input_sh=X_train_scaled.shape)
model.compile(loss="mse", optimizer="nadam")
history = model.fit(X_train_scaled, y_train, epochs=2)
y_pred = model.predict(X_test_scaled)
```

Added var to init. Weird because i didnt have too do it on mine colab and jupyterlab

**Comment by 2kich** [comment]
Yeah, I did the same, seems it's catch something from the context.  I always do some test isolated to make sure there is no any affection from the other code.

**Comment by lukebor** [comment]
@2kich @nickstegmeier I found out that when you comment line with:

super().build(batch_input_shape)   

It works without editing. Wondering why calling super().build fails. There is workaround with customizing train_step function

**Comment by kasrahabib** [comment]
Hi everyone,

From the explanation in chapter 12: "By adding this reconstruction loss to the main loss, we will encourage the model to preserve as much information as possible through the hidden layers—even information that is not directly useful for the regression task itself."

What made me confused is, he never explicitly added both losses, so:
(1) is add_loss() method adds both losses in the background
(2) or add_loss() is appending the custom loss to the model's losses list, and both are considered as separate losses during the training.

I am asking (2) question is because when I read the add_loss() documentation, what I understand is that this method only appends the custom loss to the model's losses list. There was nothing said about any mathematical operation such as adding?

And one more thing the log result on the book and the one with the workarounds are different; on the book, it logs both losses (1) the main loss and (2) the reconstruction_error. Please see it below:
'''
Epoch 1/5
11610/11610 [=============] [...] loss: 4.3092 - reconstruction_error: 1.7360
Epoch 2/5
11610/11610 [=============] [...] loss: 1.1232 - reconstruction_error: 0.8964
[...]
'''
But, for the case of workarounds, we only get one loss, so my question is:

(1)  is it the main loss, 
(2) is it the custom loss, 
(3) or somehow a combination of both. 

If the (3) is the answer, then how Keras compute it?


Thanks in advance!

**Comment by ageron** [comment]
Hi everyone,

Thank you all for the great discussion, and sorry for the late response.

Due to an issue introduced in TF 2.2 ([#46858](https://github.com/tensorflow/tensorflow/issues/46858)), it is currently not possible to use `add_loss()` along with the `build()` method. So the code in the notebook differs from the book: I create the `reconstruct` layer in the constructor instead of the `build()` method. I hope this gets resolved soon. Unfortunately, this means that the number of units in this layer must be hard-coded (alternatively, it could be passed as an argument to the constructor).

```python
class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
        self.reconstruct = keras.layers.Dense(8) # workaround for TF issue #46858
        self.reconstruction_mean = keras.metrics.Mean(name="reconstruction_error")

    #Commented out due to TF issue #46858, see the note above
    #def build(self, batch_input_shape):
    #    n_inputs = batch_input_shape[-1]
    #    self.reconstruct = keras.layers.Dense(n_inputs)
    #    super().build(batch_input_shape)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        if training:
            result = self.reconstruction_mean(recon_loss)
            self.add_metric(result)
        return self.out(Z)
```

This version works fine with TF 2.4.1. You can see it in action [in Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/12_custom_models_and_training_with_tensorflow.ipynb#scrollTo=JLuogplxJQrj), which now defaults to TF 2.4.1.

@kasrahabib, when a model has multiple losses, they are added together to compute the final loss. The sum can be a weighted sum, in some cases. For example, when a model has multiple outputs, you can specify a different loss for each output, as well as a weight for each loss (note the `loss_weights` when compiling the model):

```python
import numpy as np
import tensorflow as tf
from tensorflow import keras

np.random.seed(42)
tf.random.set_seed(42)

n_features = 5
n_samples = 100
X_train = np.random.rand(n_samples, n_features)
y_train = np.random.rand(n_samples, 1)

z = in_ = keras.layers.Input(shape=[n_features])
z = keras.layers.Dense(100, activation="relu")(z)
z = keras.layers.Dense(100, activation="relu")(z)
out1 = keras.layers.Dense(100, activation="relu")(z)
out2 = keras.layers.Dense(100, activation="relu")(z)

model = keras.models.Model(inputs=[in_], outputs=[out1, out2])
model.compile(loss=["mse", keras.losses.Huber()], loss_weights=[1.0, 2.0])
history = model.fit(X_train, [y_train, y_train], epochs=3)
print(model.loss)
```

So the answer to your question is your option (3): a combination of both. Indeed, `add_loss()` adds custom losses to the main loss. All the losses (custom losses and the main loss) are simply added together.

Hope this helps.

**Comment by kasrahabib** [comment]
@ageron,
Thanks for the kind reply!
Yes. for me it is clear now ☺️
