### ISSUE TITLE
Chapter 3: error when trying to pull a row from Pandas DataFrame

### ISSUE THREAD

**Issue by gabrielsaintangel** [ageron/handson-ml2#362]
`import matplotlib as mpl
import matplotlib.pyplot as plt

some_digit = X[0]
some_digit_image = some_digit.reshape(28, 28)
plt.imshow(some_digit_image, cmap=mpl.cm.binary)
plt.axis("off")

save_fig("some_digit_plot")
plt.show()
`

Running this cell gives the error **KeyError: 0**

`The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-12-54b1ca00dab3> in <module>
      4 import matplotlib.pyplot as plt
      5 
----> 6 some_digit = X[0]
      7 some_digit_image = some_digit.reshape(28, 28)
      8 plt.imshow(some_digit_image, cmap=mpl.cm.binary)

~/Desktop/machine-learning-practice/venv/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~/Desktop/machine-learning-practice/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 0
`

**Comment by xMarkusSpringerx** [comment]
How did you resolve this? I got the same error few days ago.

**Comment by ageron** [comment]
Thanks for your feedback. It looks like your dataset is a Pandas DataFrame, when it should be a NumPy array. This is probably due to a change in the function `fetch_openml()` which occurred in Scikit-Learn 0.24: it now returns a DataFrame by default. To prevent this from happening (and hopefully fix the issue), you should pass `as_frame=False` when calling the `fetch_openml()` function. I fixed a few weeks ago in the notebooks, so you can just git pull the latest code.

Hope this helps.
