### ISSUE TITLE
Chapter 9 - Exercise 11: random_state set to num_clusters in hyperparameter pipeline

### ISSUE THREAD

**Issue by martmor123** [ageron/handson-ml2#366]
Hi, the random_state of the hyperparameter pipeline is been set to num_clusters instead of 42: 

![Ch 9 Ex 11 Pipeline Bug](https://user-images.githubusercontent.com/61256518/104913340-741ebe80-595b-11eb-8e57-e2e4e05fb6aa.png)

**Comment by ageron** [comment]
Thanks for your feedback. Yes, I believe I did this on purpose. If I remember correctly, my rationale was that `random_state=42` might be unlucky and lead to poor k-means initialization. Changing the `random_state` at each step ensures that unlucky draws will be rare. However, arguably it makes comparing the different values of `n_clusters` a bit less reliable, since part of the performance difference may come from the `random_state` hyperparameter. I just plotted the scores we get with both options, and frankly it does not make much difference (see the graph below) so I'll change it to `random_state=42` to make things simpler.

![image](https://user-images.githubusercontent.com/76661/108425485-65e7f900-729f-11eb-96ad-425187775c01.png)

Thanks again! 👍
