### ISSUE TITLE
MAIN DIFFICULTY IS SMALL NUMBER OF OBSERVATIONS FOR  EACH  UNIQUE VALUE 

### ISSUE THREAD

**Issue by Sandy4321** [ageron/handson-ml2#384]
what to do with small number values for categorical features to tune  deep  neural network
for example categorical  feature "ABC"   has 80 categorical values, but each value observed in train data only ~ 30 times
or another example 
data 1 million rows for example 20 categorical features 
each feature has unique 570 categorical values then in average 140 observations for one unique value 140~ = 100000 / 570

MAIN DIFFICULTY IS SMALL NUMBER OF OBSERVATIONS FOR  EACH  UNIQUE VALUE

**Comment by ageron** [comment]
Hi @Sandy4321 ,
Thanks for your interesting question.

There's no right answer, but there are a bunch of things you can experiment with to find what works best in your use case. To make things more simple and concrete, I'll pretend we're talking about a single `city` attribute which has many distinct values in the dataset.

* Such a category typically follows a power law, meaning that a few categorical values are very frequent, and others are very rare. You could try lumping together all the rare cities into a single "rare" category.
* If you have more time, you could do something a bit fancier. For example, any city which appears less than 1,000 times in the dataset could be replaced by its state and perhaps an indication of its size or type. For example, if the city "Clarksdale" appears rarely in the dataset, you could replace it with "Mississippi_small" because it's a small city in Mississippi. This way, all the small cities in this state will be lumped together, and hopefully this will give useful signal to the model.
* You could replace the attribute with a few numerical attributes of relevance to the task at hand. For example, if you're building a model to predict who people will vote for, you could replace the city attribute with a few political statistics about that city, such as the ratio of people who voted for each party in the previous general elections.
* You could use a pretrained embedding for the attribute. Of course, the embedding would need to have been trained on a similar task, or else it might not be relevant.
* If you cannot find a pretrained embedding on the web, you can train your own on a different dataset for which you can gather a lot of data from the web that are relevant to your task. For example, if you are trying to build a model to predict who people will vote for, then you can try downloading plenty of relevant data (millions and millions of samples) and train a model to do something relevant, depending on what data you've gathered. For example, you may build a model that predicts what party the city's mayor belongs to. You would want your model to use an embedding of the city attribute as one of the inputs. Once the model is trained and performs well on this "side-task" (predicting the mayor's party), then you can take the trained embedding and use it in your actual task (predicting who people will vote for at the next general elections). Hopefully, the trained embedding will be useful to your actual task.

Hope this helps!

**Comment by Sandy4321** [comment]
thanks for great answer

pls let me know if you meet more repos about this
