### ISSUE TITLE
Feature Importances

### ISSUE THREAD

**Issue by stack-raghav** [ageron/handson-ml2#389]
On-Page 79( Chapter 2), we display the feature importance with attribute names.
Median-Income has the largest value but it's written in the book that near bay, ocean proximity are the most important features.
Please, someone, explain this to me.

**Comment by ageron** [comment]
Hi, thanks for your question.
The Median-Income is the most important feature, and the second most important is the INLAND feature, which is one of the possible values of the original ocean-proximity feature. However, the over values of the ocean-proximity feature (i.e., <1H OCEAN, NEAR OCEAN, NEAR BAY and ISLAND) don't seem to be very important (they have the lowest importance).  This is why the book says that we can **drop** most of the ocean proximity features, since they have very low importance.

![image](https://user-images.githubusercontent.com/76661/109456419-ac1e3300-7abd-11eb-82ee-073d680868cc.png)

Hope this helps.

**Comment by stack-raghav** [comment]
Thank you so much!
