### ISSUE TITLE
[QUESTION] Is it still worth it to read the first edition from Chapter 11?

### ISSUE THREAD

**Issue by OldIMP** [ageron/handson-ml2#410]
First of all, thx a lot for the great book!

I happen to just begin reading the first edition a while ago & was reaching Chapter 11 before I found out that there's already a 2nd edition. I looked through your detailed [Changes in the Second Edition](https://github.com/ageron/handson-ml2/blob/master/changes_in_2nd_edition.md) & find out that pretty much from Chapter 11 was rewritten (TF2, Keras, etc.).

Therefore I need your sincere opinion: Is it still worth it to read the first edition from Chapter 11? How much of the first edition from Chapter 11 is outdated? Should I stop immediately & switch to the 2nd edition?

Sry if this issue is inappropriate here & thx for your answer!

BR!

**Comment by ageron** [comment]
Hi @OldIMP ,
Thanks for your question. If you can get the 2nd edition, I really recommend it, TensorFlow 2 is a huge improvement over TensorFlow 1, it's much simpler and more powerful, and I also added quite a lot of things in the 2nd edition.
That said, if you would prefer to keep reading the 1st edition, that's fine as well: the content is still valid, and it will still be useful. The hardest thing will be "unlearning" the graph mode philosophy when you move to TensorFlow 2, as everything is "eager". For example, `tf.constant(1) + tf.constant(2)` just returns a tensor equal to 3, instead of returning a graph that you can later execute to get the result. Under the hood, TensorFlow 2 still uses graph, but they are generated automatically. Moreover, Keras is now tightly integrated into TensorFlow 2, and it's preferred over the old TensorFlow estimators API.

I hope this helps.

**Comment by OldIMP** [comment]
Thank u very much for the detailed answer!

I'll try to get my "hands on" the 2nd edition when possibile. Before that, I'll continue skimming over the rest chapters and just ignore technical details like graphs, TF estimators API & tf.contrib, etc. & focus more on the theory part.
