### ISSUE TITLE
Chapter2 scores difference in cross-validation for same model

### ISSUE THREAD

**Issue by Dongmin-ZH** [ageron/handson-ml2#413]
Hi, may I ask the reason for the difference in cross_val_score. For example, we are training a random forest classification,

```
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=100, random_state=42)
forest_reg.fit(housing_prepared, housing_labels)

scores = cross_val_score(forest_reg, housing_prepared, housing_labels,scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-scores) 

def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

display_scores(forest_rmse_scores)
````

gives result
```
Scores: [49953.20670669 47815.79539241 50966.99488639 52744.92174639
 50169.62867904 53916.85877306 48959.50703799 47996.95229844
 53255.80024686 50472.85926983]
Mean: 50625.25250370881
Standard deviation: 2015.5004421317394
```

However, when it comes to
 `pd.Series(np.sqrt(-scores)).describe()`
the result is:
```
count       10.000000
mean     50625.252504
std       2124.524007
min      47815.795392
25%      49207.931955
50%      50321.243974
75%      52300.440031
max      53916.858773
dtype: float64
```

There are two stds with same mean for one score list, may I know the reason? Or may I know which one should I take?
Thx a lot. :p

**Comment by ageron** [comment]
Hi @Dongmin-ZH ,

Nice observation! Indeed, there's a little difference between `pd.Series(a).std()` and `np.std(a)`. Both Pandas's `std()` and NumPy's `std()` have a `ddof` argument, but it is set to 1 by default in Pandas, and to 0 by default in NumPy. If you set `ddof` to the same value, you get the same result:

```pycon
>>> import numpy as np
>>> import pandas as pd
>>> 
>>> a = np.array([1., 2., 3., 4., 5., 6., 7.])
>>> np.std(a)
2.0
>>> pd.Series(a).std()
2.160246899469287
>>> pd.Series(a).std(ddof=0)
2.0
```

DDOF stands for "Delta Degrees of Freedom".  Let's see how it is used by defining our own `std()` function:

```pycon
>>> def std(a, ddof=0):
...     return np.sqrt(np.sum((a - a.mean())**2) / (len(a) - ddof))
... 
>>> std(a, ddof=0)
2.0
>>> std(a, ddof=1)
2.160246899469287
```

It does not make much of a difference when the array is large, but it is quite significant for small arrays.

So what is it about?

Suppose you want to measure the standard deviation of women's height in China. If you had access to the height of every single woman in China, you could just compute the standard deviation using `ddof=0`, and that would be absolutely fine. But you can't measure so many people, so instead you randomly sample a number of Chinese women (say 20). If you compute the standard deviation of the sample using `ddof=0`, this will give you a *biased estimate* of the population's standard deviation: the estimate will likely be too small compared to the population's standard deviation.

To convince yourself that this is the case, consider the fact that `a.mean()` is used in the computation of `std(a)`. And notice that this is the sample mean, not the population mean. It's very unlikely that the sample mean would just happen to be exactly right. It's most likely to be slightly off (and the smaller the sample, the more likely that is). So by using the sample mean in the computation (instead of the population mean, which we don't have access to), we're likely underestimating the deviation to the population mean, and thus we are likely underestimating the population's standard deviation.

To correct the estimator and make it much less biased, we must use `ddof=1`. This is called Bessel's correction. For more details, check out [this page](https://en.wikipedia.org/wiki/Standard_deviation#Corrected_sample_standard_deviation).

In short, when you're measuring standard deviation on an entire population, you should use `ddof=0`, but if all you have is a sample (but you still want an estimate of the population's standard deviation), then you should use `ddof=1`.

But the good news is that it makes very little difference when the sample is large enough.

So should we be using `ddof=0` or `ddof=1` when we compute the standard deviation of the cross-validation scores? Well arguably `ddof=1` would be preferable, since the 10 cross-validation scores we got were measured on 10 randomly sampled sets, but we could obtain many more scores on other randomly sampled validation sets. In other words, the 10 scores we got are just a sample, and therefore we should use `ddof=1`.

But in this case it does not matter much since we're comparing multiple training models, and we're using the same *biased* estimator for all of them.

I hope this is clear! As Blaise Pascal said: I wrote you a long letter because I didn't have time to write a shorter one. ;-)

**Comment by Dongmin-ZH** [comment]
Thank you so much! This "long letter" really helps me a lot. Now I can totally cope what I learned in statistics to machine learning.

**Comment by Dongmin-ZH** [comment]
Thank you so much! This "long letter" really helps me a lot. Now I can totally cope what I learned in statistics to machine learning.
