### ISSUE TITLE
Classification section, key error

### ISSUE THREAD

**Issue by fathrenheit** [ageron/handson-ml2#420]
I don't know if anyone came across to this but when I evaluate the [6], I am getting a "key error".
I checked if I made a syntax error but everything was fine. Then I figure it out; when I try to bind X[0] to some_digit variable, I was actually trying to bind the very first row to a variable and that was the error. I fixed this by;

```
some_digit = X.iloc[0].to_numpy()
some_digit_image = some_digit.reshape(28, 28)
```

**Comment by binzhango** [comment]
[https://stackoverflow.com/a/60116070/11131288](url)

**Comment by binzhango** [comment]
[https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.Series.reshape.html](url)

**Comment by ageron** [comment]
Hi @fathrenheit ,

Thanks for your feedback. It looks like your dataset is a Pandas DataFrame, when it should be a NumPy array. This is probably due to a change in the function `fetch_openml()` which occurred in Scikit-Learn 0.24: it now returns a DataFrame by default. To prevent this from happening (and hopefully fix the issue), you should pass `as_frame=False` when calling the `fetch_openml()` function. I fixed this a couple months ago in the notebooks, so you can just `git pull` the latest code.

Hope this helps.

**Comment by fathrenheit** [comment]
Thank you for replying. Since I've been following your book from the printed version, I couldn't think of it was because of fetch_openml() function. Now it is clearer then before. Thank you again.
