### ISSUE TITLE
Please check errata

### ISSUE THREAD

**Issue by almorozovv** [ageron/handson-ml2#43]
https://www.oreilly.com/catalog/errata.csp?isbn=0636920142874

**Comment by almorozovv** [comment]
Thank you for your attention to the problem.  I didn’t know about the situation with Chrome. I’m sorry to bother you.

**Comment by ageron** [comment]
Thanks for your feedback and your understanding, Aleksandr. 👍 

For people visiting this page, the issue is that MathML is not rendered properly when reading my book on the Safari platform using the Chrome browser. Using another browser such as Firefox or Safari works around the issue. O'Reilly is working on fixing this issue for Chrome users, and in the meantime I asked them to display a warning about this problem, advising them to use Firefox or Safari.
