### ISSUE TITLE
[QUESTION] Book's used graphics

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml2#468]
This is not a technical issue.
I am interested to know what is the tool used for drawing graphics for the book?

Example:
<img width="581" alt="Screenshot 2021-09-17 at 17 23 40" src="https://user-images.githubusercontent.com/29026528/133811577-aa64d2d1-5ebf-4550-9aac-d54e91703814.png">

**Comment by ageron** [comment]
Hi @kasrahabib,

I use Google Slides, just because I'm used to it. There are plenty of other tools, but I find this one nice and simple, and it's easy to share it with reviewers and translators. I just wish there were keyboard shortcuts to toggle "Snap to guides", "Snap to grid" and "Zoom 200%", I use them quite a lot.

To get high-res images of each slide (which is needed by O'Reilly for printing), I first export the whole presentation to PDF:

![image](https://user-images.githubusercontent.com/76661/133982195-7e6ddfed-a010-4278-8114-4c7a77300b9f.png)

Then I use the following command to get high-res PNG images (the `convert` command comes with [ImageMagick](https://imagemagick.org/index.php)):

```bash
convert -verbose -density 300 -trim +repage google_slides.pdf diagram_%03d.png
```

This creates one 300dpi PNG image per slide.

Hope this helps.

**Comment by kasrahabib** [comment]
Hi @ageron,

You are very kind! ☺️
