### ISSUE TITLE
github pages incomplete

### ISSUE THREAD

**Issue by ctdarwell** [ageron/handson-ml2#471]
Do you realise there are chunks of your github pages missing? Eg: https://github.com/ageron/handson-ml2/blob/master/math_differential_calculus.ipynb

Immediately underneath the text: "Example: finding the derivative of x -squared" and other places

**Comment by ageron** [comment]
Hi @ctdarwell ,

Thanks for your feedback!

The notebook itself is actually fine, the problem is with github's notebook viewer: it just doesn't display math equations correctly. Many people (including me) have reported this issue to github, but it's there, several years later.

That's why I wrote this on this project's home page:

![image](https://user-images.githubusercontent.com/76661/136150552-42fc8bb1-3747-449d-9204-5d96969be322.png)

The solution is easy: just use another viewer, such as [Jupyter's nbviewer](https://nbviewer.jupyter.org/github/ageron/handson-ml2/blob/master/index.ipynb).

Hope this helps.

**Comment by ageron** [comment]
I just [tweeted about this](https://twitter.com/aureliengeron/status/1445640076109647873), and I just wrote to a friend who works at github. Perhaps with enough people asking they'll spend a bit of time to fix the issue.

**Comment by ctdarwell** [comment]
Thanks for your response. I didn't see the disclaimer (sorry). However, it
did get me to finally get round to using Jupyter notebooks.

Thanks for all your work - it's very well presented
