### ISSUE TITLE
Chap 3 plot_digits, imshow, need more explaination

### ISSUE THREAD

**Issue by ladylazy9x** [ageron/handson-ml2#479]
Because the function plot_digits had not been explained in the book so I need a lot time to understand the code, I think there should be explain at least by commenting on the code for purpose of each line.

**Comment by ageron** [comment]
Hi @ladylazy9x ,

Thanks for your suggestion. I've had a few people asking me this, so I think I'll add `plot_digits()` to the book. The reason I didn't want to do this is that `plot_digits()` is a bit long and complicated and it doesn't add anything about Machine Learning, so I thought it was just off-topic. I preferred to just say that `plot_digits()` plots multiple digit images, and that's it, leaving the details for the notebook.

I've shown how to plot *one* digit in chapter 3 (`plt.imshow(some_digit_image, cmap="binary")`), and I also showed in that same chapter how to create a plot with several subplots (using `plt.subplot()`), so I thought people could easily combine both if they wanted to plot multiple images. Perhaps something like this:

```python
import matplotlib.pyplot as plt
import numpy as np

num_rows, num_cols = 2, 3
images = np.random.rand(num_rows * num_cols, 10, 10) # random 10x10 grayscale images

for row in range(num_rows):
    for col in range(num_cols):
        image_index = row * num_cols + col
        plt.subplot(num_rows, num_cols, image_index + 1) # this function is 1-indexed, hence the +1
        plt.imshow(images[image_index], cmap="binary")
        plt.axis('off')
```

If you run this code (it's fairly self-explanatory), you'll get something like this:

![image](https://user-images.githubusercontent.com/76661/136675440-7bedf582-ed3d-4837-86f7-e938c0e0d440.png)

The problem with this code is that there's quite a bit of space between the images. And back when I wrote these notebooks, I remember struggling to remove that extra space. Plus, the function was super slow for some reason. So I wrote a much more complicated implementation which creates one large image out of all the small ones (and pads it with empty images if needed), and finally just plots the one big image. Frankly it's not worth wasting time trying to understand how it works, because I just tried the simple approach today, and it seems to work fine now, except that it's still slow. I think either a Matplotlib bug has been resolved since I wrote the book, or perhaps I made a mistake back then. Here it is:

```python
import matplotlib.pyplot as plt
import numpy as np

def plot_images(num_rows, num_cols, images):
    fig, axes = plt.subplots(ncols=num_cols, nrows=num_rows,
                            sharex=True, sharey=True,
                            figsize=(num_cols, num_rows))
    fig.subplots_adjust(left=0, bottom=0, right=1, top=1, wspace=0, hspace=0)
    for row in range(num_rows):
        for col in range(num_cols):
            image_index = row * num_cols + col
            ax = axes[row][col]
            ax.imshow(images[image_index], cmap="binary")
            ax.axis('off')

num_rows, num_cols = 10, 10
images = np.random.rand(num_rows * num_cols, 10, 10)
plot_images(num_rows, num_cols, images)
```

The `fig.subplots_adjust()` call ensures there's no gap between the subplots. The rest is quite straightforward.

Hope this helps.

**Comment by ageron** [comment]
Mmh, I forgot about something. There's a figure in chapter 3 that looks like this:

![image](https://user-images.githubusercontent.com/76661/136675802-86acb688-bfc8-4b40-80d0-d0d819775180.png)

As you can see, it's split in 4 parts, each with 5x5 images. This was a bit hard to do using only subplots. Either you make 4 big images out of all the digits and then you use subplots to display these big images in a 2x2 grid, or you must use subplots containing subplots, which is not trivial. It can be done using GridSpecs (see this [StackOverflow answer](https://stackoverflow.com/a/34934631/38626)). So I'm not sure I want to change `plot_digits()` after all...

So okay, I'll explain how it works (I've added comments in the code):

```python
def plot_digits(instances, images_per_row=10, **options):
    # instances has shape [?, 784]. Each row represents a 28x28 image.
    size = 28
    # if this function is called with just (say) 3 images, but images_per_row is larger, then we should
    # fix images_per_row to make it equal to the number of images:
    images_per_row = min(len(instances), images_per_row)

    # We now reshape every image to make it 28x28 instead of a one-dimensional vector of size 784:
    images = [instance.reshape(size,size) for instance in instances]

    # Given the number of images and the number of images per row, let's compute the number of rows.
    # The following is equivalent to `ceil(len(instances) / images_per_row)`, but it doesn't require
    # `import ceil from math`:
    n_rows = (len(instances) - 1) // images_per_row + 1

    # For each row of images, we'll construct a single wide image made out of all the images in the row:
    row_images = []

    # If the number of images is not a multiple of the number of images per row, then we must pad the final
    # row with some number of empty images. Let's compute how many we need and add them to the list of
    # images:
    n_empty = n_rows * images_per_row - len(instances)
    images.append(np.zeros((size, size * n_empty)))

    # now let's loop over the number of rows:
    for row in range(n_rows):
        # Let's grab all the images from the current row:
        rimages = images[row * images_per_row : (row + 1) * images_per_row]
        # Now let's concatenate these images horizontally into a single wide image using
        # `np.concatenate()`, and let's add this wide image to the list of row images:
        row_images.append(np.concatenate(rimages, axis=1))

    # Now that we have one wide image per row, let's concatenate all of them
    # vertically into a single big image
    image = np.concatenate(row_images, axis=0)
    # And finally we can just `imshow()` this big image, forwarding any options we were given:
    plt.imshow(image, cmap = mpl.cm.binary, **options)
    # And drop the horizontal and vertical axes (and their labels):
    plt.axis("off")
```
