### ISSUE TITLE
?raw=True required when downloading files from github

### ISSUE THREAD

**Issue by edmundsj** [ageron/handson-ml2#502]
In the book, when downloading datasets from the URL's provided in the code snippets (i.e. ```https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.tgz```) you must append ```?raw=true``` to the filename for the provided code to work correctly. So the actual file URL in example 1-1 should be ```https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.tgz?raw=True```, otherwise you will just download the github webpage for the file with urllib.

**Comment by edmundsj** [comment]
This came from me getting this error when trying to run ```fetch_housing_data()```:

```
>>> fetch_housing_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordan.e/Google Drive/GTD/PhD/Software/ml/fetch_data.py", line 18, in fetch_housing_data
    housing_tgz = tarfile.open(tgz_path)
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by ageron** [comment]
Hi @edmundsj ,

Thanks a lot for your feedback. I tried to reproduce this problem, but it worked fine without `?raw=true`, so I'm a bit puzzled. I tried on both MacOS and Linux, and it worked fine. I'm using Python 3.8.
Could you please tell me which version of Python you are using, and which OS? Also, could you please try deleting `datasets/housing/housing.*` and trying again without `?raw=true`, just to check that the problem wasn't due to a temporary server-side issue? Thanks!

**Comment by ageron** [comment]
Ah, my bad, you're right, it does fail, I didn't notice that you were using `https://github.com/ageron/handson-ml2` as the `DOWNLOAD_ROOT`. The book and [the notebook](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/02_end_to_end_machine_learning_project.ipynb) use:

```python
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
```

This should work fine.

Hope this helps.
