### ISSUE TITLE
[BUG] Chapter 8 exercicse 10. convert string array into a plot.

### ISSUE THREAD

**Issue by d1amondb0t** [ageron/handson-ml2#505]
Thanks for helping us improve this project!

**Before you create this issue**
Hi,
The more I read the book, the more I'm amazed by it. THANK YOU SO MUCH FOR THIS BOOK!

Anyways, I was running the exercises and since I'm not the best with scatter plots ;(, I tried to look a bit at the exercise but I noticed that the input will be an array of string and not of integer, so the plot won't show on the plot and will throw an issue.

**Describe the solution you'd like**
What we desire is to have a plot which shows the 10 different numbers in the MNIST reduced dataset onto the scatter plot, where each color represents a different number from the dataset. The proposed solution in the notes are the following

```python
np.random.seed(42)

m = 10000
idx = np.random.permutation(60000)[:m]

X = mnist['data'][idx]
y = mnist['target'][idx]

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42)
X_reduced = tsne.fit_transform(X)

plt.figure(figsize=(13,10))
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=y, cmap="jet")
plt.axis('off')
plt.colorbar()
plt.show()
```

And the output of this block of code is this:
![image](https://user-images.githubusercontent.com/81024527/142434050-b04136ea-2ef3-4f86-b029-cdcfc149bf59.png)

**Describe alternatives you've considered**
The alternative that I have considered for this is to simply iterate threw the the array and convert the values from string into integers with the following line before plotting the scatter plot.

```python
plt.figure(figsize=(12,8))
**y = [int(i) for i in y]**
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=y, cmap="jet")
plt.axis('off')
plt.colorbar()
plt.show()
```

And the results is shown below:
![image](https://user-images.githubusercontent.com/81024527/142434716-e88107b7-5d67-4345-a555-15e5c1c457df.png)

I tried looking at the result in google colabs and to see the code there, but for some reason, it wouldn't redirect me to the colab when I clicked on it.

**Comment by ageron** [comment]
Hi @d1amondb0t ,

Thanks for your very kind words, I really appreciate it, and I'm glad you enjoy my book! Also, thanks a lot for your feedback, great catch! When I wrote this notebook, MNIST was loaded using `fetch_mldata()` instead of `fetch_openml()`, and it returned integer targets instead of string targets. `fetch_mldata()` is now deprecated because the website it relies on is dead. So we have string targets now, which explains why the code fails: I don't understand how I missed this until now, sorry about that. In every other notebook, I was careful to use `y = mnist.target.astype(np.int8)`, which solves the issue, but for some reason, I forgot to do that in this notebook, probably because the targets are not used that much.

Anyway, the problem can be fixed as you suggested. 👍  Alternatively, just use this code:

```python
np.random.seed(42)

m = 10000
idx = np.random.permutation(60000)[:m]

X = mnist.data[idx]
y = mnist.target[idx].astype(np.int8)  # <= CONVERT STRINGS TO INTEGERS

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42)
X_reduced = tsne.fit_transform(X)

plt.figure(figsize=(13,10))
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=y, cmap="jet")
plt.axis('off')
plt.colorbar()
plt.show()
```

I'll fix the notebook now.

Thanks again! 😊

**Comment by ageron** [comment]
Oh actually, I had already fixed this in the notebook, just after MNIST is loaded, there's this line:

```python
mnist.target = mnist.target.astype(np.uint8)
```

🎉

**Comment by d1amondb0t** [comment]
oh, I didn't see it, well thanks anyways
