### ISSUE TITLE
[QUESTION] did not understand part of the code in the book

### ISSUE THREAD

**Issue by bafdada** [ageron/handson-ml2#512]
in this code:

```
def epsilon_greedy_policy(state, epsilon=0):
    if np.random.rand() < epsilon:
        return np.random.randint(n_outputs)
    else:
        Q_values = model.predict(state[np.newaxis])
        return np.argmax(Q_values[0])
```

i did not understand why only the Q_values[0] is returned and not all the Q_values.
Thanks in advance.

**Comment by ageron** [comment]
Hi @bafdada ,
Thanks for your question. When in doubt regarding indexing, make sure to print the shapes. In this case, state is a 1D array of shape [n] where n is the size of the state. It represents a single state. The model expects an array with one row per state, which is why we pass it state[np.newaxis]. This adds a first axis of size 1, so the shape is [1, n].
The model makes one prediction per state, so in this case just one prediction, so the shape of Q_values is [1]. Since it just has one element (the single prediction for the single state we gave the model), we can return that single value using Q_values[0].

I hope this helps!
