### ISSUE TITLE
[QUESTION] Clarification request regarding BPTT

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml2#515]
@ageron thanks for the continuous efforts and your time answering questions.

I had a look thorough the book's diagram regarding backpropogation through time (Figure 15-5) and I am not sure if I got the meaning of the book's diagram correctly.

What I understand is that we will have a sum of loss over all time steps (or some), then we change the weights back in time with respect to the selected outputs. What I did not get is, is the **(W, b)** related to time step ```X0``` and ```X1```, are they being changed with respect to only ```Y4``` or once in respect to ```Y2```, once ```Y3``` and once ```Y4```. 

My current understanding is that **Ws** and **bs** in time step 0, 1 and 2 are each changed once per ```Y2```, once ```Y3``` and once ```Y4```. And, the **Ws** and **bs** in time step 3 is changed two times once with respect to ```Y3``` and once ```Y4``` and so on.

**Comment by ageron** [comment]
Hi @kasrahabib ,

Thanks for your feedback. There's going to be one update per black arrow going to the recurrent cell (i.e., one per arrow going down or left into a W,b cell). Remember that it's actually the same cell represented several times, so these multiple updates will all be to the same W,b parameters. All updates will happen simultaneously *after* the gradients are computed during the backward phase.

Check out appendix D, especially figure D-3.  Notice that there are two paths going back to `y`, and they simply add up. The same happens in an RNN since there are multiple paths going back to W and b, and all these paths simply add up.

Hope this helps.

**Comment by kasrahabib** [comment]
Hi @ageron,

Thank you very much! ☺️
Now everything is crystal clear regarding ```bptt```; example ```D-3``` was the best example.
It might be a good idea to add a reference to this specific example if you are planning to make a new Edition of the book.

I also read the paper “Backpropogation through time: What it does and how to do it”, which gave me more insight about it. 

One thing (maybe) missing in the paper is what happens while doing the prediction.
What happens during the prediction: do we use the same ```W```,  ```b``` and unroll the network while sending back outputs of the first prediction to the cell to produce the next prediction, in case if we are dealing with a seq-to-seq or one-to-seq architecture to have more outputs? 

Kasra ☺️

**Comment by ageron** [comment]
I'm glad everything is clear now. Thanks for your feedback and suggestions, I'm currently writing the 3rd edition, so this helps! 👍 
For predictions, indeed everything happens like in the forward phase of backproo: the network is unrolled through time and the same W and b are used at each time step (but there's no backward phase).
Cheers,
Aurélien

**Comment by kasrahabib** [comment]
Thank you very much! ☺️
