### ISSUE TITLE
[QUESTION CHAP. 3] Why does the normal dataset perform better than the scaled dataset?

### ISSUE THREAD

**Issue by heerboi** [ageron/handson-ml2#527]
Hello there!

I'm referring to the first exercise in Chapter 3 of the book. I first tried performing a GridSearchCV on the scaled dataset because I thought normalization would improve the model, but the model trained on the normal dataset performed much better, is there a particular reason as to why this happens? Or is it just by chance that the dataset itself and how the samples were organized resulted in it being worse?

Thank you!

**Comment by ageron** [comment]
Hi @heerboi ,

Thanks for your interesting question! Indeed, when training with Gradient Descent, it's generally important to scale features to ensure that they have the same order of magnitude, or else training may be very slow, as explained in chapter 4. However, I should have added that there are cases where it's not true, and it turns out that MNIST is one of them: in MNIST, the white pixels on the borders of the image have very little variance, and their values are zero or close to zero. Without scaling, they're very likely to be completely ignored by the model, and that's actually a good thing, because they don't really matter at all. But with scaling, these pixels add basically just noise, and they hurt the model's performance.

So scaling makes complete sense when you're dealing with a mix of heterogeneous features, like in the California Housing dataset. However, when dealing with images, it depends: the pixels generally have values that fall within a limited range, so they don't always need scaling. in general, I would assume that scaling should help, or at least shouldn't hurt, but occasionally, like in MNIST, it adds some noise.

I'm currently writing the 3rd edition, so I might add a note about this, thanks for bringing it to my attention! 🙏

**Comment by heerboi** [comment]
Hey there!

Thank you for your response. Your explanation makes it very clear now, especially the part about every pixel having a limited range. :)

Thank you.
