### ISSUE TITLE
[BUG] Chapter 13, the first cell in the CH13 Google Colab takes hours to run

### ISSUE THREAD

**Issue by ericrenter** [ageron/handson-ml2#532]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml2/blob/master/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml2#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml2/issues

**Describe the bug**
Please provide a clear and concise description of what the bug is, and specify the notebook name and the cell number at which the problem occurs (or the chapter and page in the book).

**To Reproduce**
Please copy the code that fails here, using code blocks like this:

```python
def inverse(x):
    return 1 / x

result = inverse(0)
```

And if you got an exception, please copy the full stacktrace here:

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in inverse
ZeroDivisionError: division by zero
```

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. MacOSX 10.15.7]
 - Python: [e.g. 3.7]
 - TensorFlow: [e.g., 2.4.1]
 - Scikit-Learn: [e.g., 0.24.1]
- Other libraries that may be connected with the issue: [e.g., gym 0.18.0]

**Additional context**

**Comment by ericrenter** [comment]
[BUG] Chapter 13, the first cell in the CH13 Google Colab hangs indefinitely (over 20 min now, will delete this report if the cell completes) after downloading a bunch of files. Presumably it is unable to finish installing TFX? I am using Chrome on Windows 10, same issue using Chrome on Windows 7, different machine.

**Comment by ageron** [comment]
Thanks for your feedback @ericrenter .
I just tried running the Google Colab for chapter 13, and indeed the first cell takes forever! As you guessed, this is because of the TFX installation. I removed `-q` to see the full output, and it looks like pip's dependency resolver isn't happy with the tensorflow version installed by default on Colab, so it tries downloading another version of TensorFlow (over 420 MB!), but it still doesn't resolve the dependency constraints, so it downloads another version (again over 420 MB), and it repeats the process many times:

```
Collecting tfx==0.21.2
  Downloading tfx-0.21.2-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 5.2 MB/s 
[...]
Collecting tensorflow<3,>=1.15
  Downloading tensorflow-2.1.4-cp37-cp37m-manylinux2010_x86_64.whl (422.0 MB)
     |████████████████████████████████| 422.0 MB 33 kB/s 
INFO: pip is looking at multiple versions of tensorflow-transform to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow-serving-api<3,>=1.15
  Downloading tensorflow_serving_api-2.1.0-py2.py3-none-any.whl (38 kB)
Collecting tensorflow<3,>=1.15
  Downloading tensorflow-2.1.3-cp37-cp37m-manylinux2010_x86_64.whl (421.9 MB)
     |███████████████████████▏        | 305.5 MB 1.2 MB/s eta 0:01:34
```

So I tried removing the version constraint for TFX, replacing `%pip install -q -U tfx==0.21.2` with just `%pip install -q -U tfx`, and this works okay (even though it outputs some errors, you can safely ignore them).

I'm guessing this issue is due to the fact that Colab updated TensorFlow to the latest version, but TFX 0.21.2 is not compatible with it, so it tries to download an older version of TensorFlow, and this breaks other dependencies.

I'll update the notebook to remove the version constraint.

Thanks again! 🙏

**Comment by ericrenter** [comment]
Fixed by author in just one day, amazing, thank you Aurelien Geron!!
