### ISSUE TITLE
Jupyter Notebook Issue using Docker on MacOS [QUESTION]

### ISSUE THREAD

**Issue by cdbaird** [ageron/handson-ml2#547]
I'm having trouble running the Jupyter notebook in the Docker container on MacOS (disclaimer: I'm brand new to Docker). I've installed the Docker Desktop App, and pulled the container using ```docker pull ageron/handson-ml2```. This appeared to download everything properly, but not into the project directory as I was expecting (presumably into one of the application directories).

I ran the container from the Docker app and opened the CLI which showed all the python packages etc. installed, but running ```jupyter notebook``` gives the following error:

```[W 18:38:22.668 NotebookApp] No web browser found: could not locate runnable browser.```

Copying the link+token into the browser address bar throws a 'refused to connect' error.

Is there anything else I should be doing to get this working?

**Expected behavior**
Expected the jupyter notebook to open automatically in the browser, and be able to view all notebooks.

**Versions **
 - OS: MacOS 10.15.7

**Comment by ageron** [comment]
Thanks for your feedback. On MacOS, docker images are stored in `~/Library/Containers/com.docker.docker/Data/vms/0/`, but in general you don't want to touch these files directly, instead you must use `docker` commands.

Did you try going through the instructions in the `docker/README.md` file? If you have `docker-compose` installed (which I believe is automatically installed along with the Docker app on MacOS), you can just run this command (replacing `/path/to/project` with the correct path to the `handson-ml2` directory):

```bash
cd /path/to/project/handson-ml2/docker
docker-compose up
```

You may get an error message like this:

```
ERROR: for handson-ml2  Cannot start service handson-ml2: Mounts denied:
The path `/path/to/project/handson-ml2` is not shared from the host and is not known to Docker.
```

In this case you need to open the docker app and go to the preferences > Resources > File Sharing, and add the path `/path/to/project/handson-ml2` to the list of directories that docker is allowed to access, then try again.

FYI, here's what happened when you connected to a container and launched jupyter: you were running commands inside the container, which is similar to remotely connecting to a remote server. You can start jupyter inside the container, but you cannot open a web browser from inside the container: it has no web browser, and even if you installed one, it wouldn't work since the container has no screen either. So instead you must open your regular web browser on your machine and make it connect "remotely" to the jupyter server running inside the container. But for this to work, you must map a TCP port on your machine to a TCP port on the container. The `docker-compose.yml` file in the `handson-ml2/docker` directory contains instructions for `docker-compose` to setup the ports correctly: it maps port 8888 on your own machine to port 8888 in the container. This way, when jupyter starts in the container, it is accessible "remotely" at http://127.0.0.1:8888 on your machine. Note that `docker-compose up` will fail if there's already another software listening on port 8888 on your machine (such as a jupyter instance already running on your machine).

Also note that `docker-compose up` also maps port 6006 on your machine to port 6006 in the container: this is needed if you want to connect your browser to the TensorBoard server (in case you start one in the container).

Lastly, `docker-compose.yml` also maps the `/path/to/project/handson-ml2` directory on your machine to the `/home/devel/handson-ml2` directory inside the container: without this, jupyter wouldn't be able to open any notebook, since the container would not have access to anything on your machine.

If you don't want to use `docker-compose` for some reason (not sure why), you can use the following docker command instead (`docker-compose` is just a thin wrapper that runs complicated commands like this for you):

```bash
cd /path/to/project/handson-ml2
docker run -it --rm -p 8888:8888 -p 6006:6006 -v /path/to/project/handson-ml2:/home/devel/handson-ml2 ageron/handson-ml2:latest /opt/conda/envs/tf2/bin/jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser
```

The `-p` option takes care of mapping TCP ports. The `-v` option maps directories (aka "volumes"). The last part of the command (starting at /opt/conda...) is the command that will be run inside the container: it starts the jupyter server, listening on port 8888, and it tells jupyter not to try opening a web browser (since there's no browser inside the container). Once the jupyter server is started, you must manually open your web browser on your machine and go to http://127.0.0.1:8888 (in case you're not familiar with networking, 127.0.0.1 is the address of the local host, i.e., your own machine).

The `-it` option makes the docker container interactive: for example, you can type Ctrl-C to stop the jupyter server.

The `--rm` option means that docker will automatically delete the container once it is interrupted. This will delete any data inside the container, which is usually fine since the notebooks are not actually inside the container, so no important information is lost. This is optional, but I personally prefer to work this way, keeping all important data on my own machine, and not cluttering my machine with may interrupted containers.

Hope this helps.

**Comment by cdbaird** [comment]
Thank you for the detailed response! It seems that on MacOS, the docker images are all stored within one large image file, called ```Docker.raw```. So there doesn't seem to be an easy way to access the individual containers to run the ```docker-compose``` command, or any other command that requires the container as a target. 

I was able to access the files just by cloning the git repo, and ran ```docker-compose build``` in the ```docker``` subdirectory. This threw the following error during the build:

```
=> ERROR [ 4/12] RUN printf "\n    - pyvirtualdisplay" >> /tmp/enviro  124.4s 
------                                                                         
 > [ 4/12] RUN printf "\n    - pyvirtualdisplay" >> /tmp/environment.yml     && conda env create -f /tmp/environment.yml     && conda clean -afy     && find /opt/conda/ -follow -type f -name '*.a' -delete     && find /opt/conda/ -follow -type f -name '*.pyc' -delete     && find /opt/conda/ -follow -type f -name '*.js.map' -delete     && rm /tmp/environment.yml:
#8 0.855 Collecting package metadata (repodata.json): ...working... done
#8 57.09 Solving environment: ...working... Killed
------
executor failed running [/bin/sh -c printf "\n    - pyvirtualdisplay" >> /tmp/environment.yml     && conda env create -f /tmp/environment.yml     && conda clean -afy     && find /opt/conda/ -follow -type f -name '*.a' -delete     && find /opt/conda/ -follow -type f -name '*.pyc' -delete     && find /opt/conda/ -follow -type f -name '*.js.map' -delete     && rm /tmp/environment.yml]: exit code: 137
ERROR: Service 'handson-ml2' failed to build : Build failed
```

In any case, I can work with all the notebooks now from the git repo, so the docker issues aren't preventing me from making progress, but I'd appreciate any insight you could offer.

Cheers

**Comment by ageron** [comment]
Oh thanks pointing this issue when building the image, it's possible that there are currently some incompatibilities between packages, I will check this out.

Let me clarify the first steps:

* First, clone the handson-ml2 repository on your machine. Let's say it's located in `/path/to/project/handson-ml2`.
  * Note: the "handson-ml2" docker image only contains python, jupyter and all the required libraries, it does *not* contain the handson-ml2 repository, it doesn't include any Jupyter notebooks. In general, it's preferable to put only software inside docker images, not data that you may want to modify. That's why I kept the notebooks out, and why you must clone the repo on your own machine.
* Second, open a terminal on your machine and go to the `/path/to/project/handson-ml2/docker` repository, and run `docker-compose up` (this command must be run on your machine, *not* inside a container). This will download the `ageron/handson-ml2` image if needed, then it will starts a container with this image and run jupyter inside it, forwarding the appropriate ports, and making the `/path/to/project/handson-ml2` directory on your machine accessible directly from inside the container at `/home/devel/handson-ml2`.
* Third, open a web browser on your machine, and navigate to http://127.0.0.1:8888

I hope this helps.

**Comment by cdbaird** [comment]
Thanks for the clarification. I've managed to get it working now with those instructions. It wasn't clear to me from the ```docker/README.md``` that I should clone the repo first. 

This now appears to be working. Thanks again for the rapid and detailed answers!

**Comment by ageron** [comment]
Hi Chris,
I'm glad it finally worked! I'm sorry the instructions weren't clear enough, I'll try to improve them based on this discussion, so thanks for your feedback!
