### ISSUE TITLE
Feature Columns and Functional API

### ISSUE THREAD

**Issue by IanQS** [ageron/handson-ml2#6]
Hey there! 

First off, super huge fan and very excited for the final product (bought the first book and loved it)

I thought it would be worth noting in the book that `tf.feature_column` doesn't seem to work with tf2.0 as of this time of writing (May 13 2019)

Specifically stuff in Chapter 13

```
columns_without_target = columns[:-1]
model = keras.models.Sequential([
    keras.layers.DenseFeatures(feature_columns=columns_without_target),
    keras.layers.Dense(1)
])
model.compile(loss="mse", optimizer="sgd", metrics=["accuracy"])
model.fit(dataset, steps_per_epoch=len(X_train) // batch_size, epochs=5)
```

based on [https://github.com/tensorflow/tensorflow/issues/28111](https://github.com/tensorflow/tensorflow/issues/28111) and [Unable to use FeatureColumn with Keras Functional API](https://github.com/tensorflow/tensorflow/issues/27416)

**Comment by ageron** [comment]
Hi @IanQS ,

Thanks a lot for your kind words and your feedback regarding the features API.  AFAICT, the issues you point to only affect the Functional API, I just ran the notebook for chapter 13, it worked fine for me. Did you get any exception? If so, could you please copy the full stacktrace here? I will add a message in the notebook about this issue (but I try not to add to many messages like this in the book itself, because presumably all the important bugs like this will be resolved by the time TF 2.0 is released, which hopefully will be before my book is released).

**Comment by IanQS** [comment]
>  AFAICT, the issues you point to only affect the Functional API, I just ran the notebook for chapter 13, it worked fine for me. Did you get any exception? If so, could you please copy the full stacktrace here?

Ahh, yeah, I should have specified in the message (and not just the title) that it is only an issue on the functional API. I suppose I brought it up because in [Chapter 10 - Functional API](https://github.com/ageron/handson-ml2/blob/master/10_neural_nets_with_keras.ipynb) one might get the impression that it would work out of the box like the sequential module.

I brought it up because I am more used to Tf1.x, so the functional style is more comfortable for me. I spent a TON of time on [tf 2 alpha - structured data tutorial](https://www.tensorflow.org/alpha/tutorials/keras/feature_columns) trying to get feature_columns working with the functional API and just wanted to help others avoid diving down the same rabbit hole

**Comment by ageron** [comment]
Thanks for your feedback @IanQS!
