### ISSUE TITLE
Installation on Windows - %matplotlib inline problems

### ISSUE THREAD

**Issue by JulesVerny** [ageron/handson-ml2#62]
Yes I know ML practioners all want us to use Linux and avoid Windows.  But some of us do use Windows 10 for Machine Learning and Tensorflow. 

I have Anaconda installed, and have created a tensorflowenv to process the new TF2.0 API.  I have used your environment.yml.  This appears to work after I had to explicitly install tensorflow-gpu 2.0 into the Conda Environment and upgraded to Cuda 10.x Nvidia drivers. I canrun the new TF.keras Api and training.  But I would like to run your code. 

However this environment does not support %matplotlib inline for the basic display of plots in jupyter notebooks. pillow was installed but I still get the error:
**from . import _imaging as core
     if __version__ != getattr(core, "PILLOW_VERSION", None):
ImportError: DLL load failed: The specified module could not be found.**  

My other environments with this instruction do work. So its not necessarily a Windows problem, so its looks like a package dependency within this particular Conda environment that does not enable me to run this Instruction.  All rather curious. 

I appreciate that you, Aurelien, don't run on Windows, and cannot help, but perhaps if another reader has reconciled  this issue, it would be very helpful.

**Comment by ageron** [comment]
Hi @JulesVerny,
Thanks for your detailed question. Indeed, it's hard for me to help since I don't have a Windows 10 computer to play with, but I can try!
Could you please run `conda list` in this conda environment as well as in a conda environment where `%matplotlib inline` works, and post both lists here so I can compare the installed packages?

You could also post the diff directly, if you want. Something like this:

```bash
$ conda list --name tensorflowenv > bad.packages.txt
$ conda list --name mygoodenv > good.packages.txt
$ diff -y good.packages.txt bad.packages.txt
```

**Comment by JulesVerny** [comment]
Hi Aurelien
I wasn't really expecting you to personally look into this frustration. 
I have done a conda list against my base Anaconda environment where the Inline instruction works and then on my tensorlofenv where it doesn't.  Please see attached:

[good.packages.txt](https://github.com/ageron/handson-ml2/files/3828495/good.packages.txt)
[bad.packages.txt](https://github.com/ageron/handson-ml2/files/3828498/bad.packages.txt)
[Difference.txt](https://github.com/ageron/handson-ml2/files/3828496/Difference.txt)

I am sorta resigned on doing the Tensorflow/Keras nueral networks in a Linux environment. I do know that the OpenGym ATARI environmens for RL only work on Linux.

**Comment by ageron** [comment]
Thanks Jules. It looks like your working environment uses pillow 5.4.1 and matplotlib 3.0.3, while the non-working environment uses pillow 6.2.0 and matplotlib 3.1.1. Perhaps you could try installing the working versions of these packages?

A few more ideas: since the error is that a DLL is not found, it might be a path issue? For example, perhaps the Jupyter kernel is not running in the environment you expect? Perhaps the `LOAD_LIBRARY_SEARCH` environment variable is set? Or perhaps you need to add a Jupyter kernel for your environment?

```
conda activate tensorflowenv
ipython kernel install --name "tensorflowenv" --user
```

Then make sure to select the tensorflowenv kernel in Jupyter.

As you can probably tell, the last time I used Windows for work was around 1999. ;-)

**Comment by ageron** [comment]
Closing this issue. Please reopen if the problem persists.
