### ISSUE TITLE
Chapter 13 - section on preprocessing the input features missing

### ISSUE THREAD

**Issue by genemishchenko** [ageron/handson-ml2#69]
Hi Aurelien,

Within the Jupyter note for Chapter 13 on data processing with TF, I don't see the section titled "Preprocessing the Input Features" that you have in your book (a fairly long one, before "TF Transform").

Instead, I see "The Features API" section in the note (which is not in the book).
Looks like cool stuff, but I get errors when running it.

Thanks.
Gene.

**Comment by ageron** [comment]
Thanks for your feedback, Gene. You're right, I should add the code for that section in the notebook, thanks for pointing it out. Funny story: I spent a few weeks working on writing the part about the Features API, then one of the reviewers from the TF team reviewed the book and recommended that I drop that section because "it's not future proof". Indeed, the TF team is moving away from the Estimators API and the Features API (which go hand in hand). So I scratched everything I had written and started again from scratch! Unfortunately, it seems that I forgot to update the notebook. I'll try to do this asap (but I'm currently very busy as I'm moving to New Zealand shortly, so it might take a few weeks).

I'm surprised that you're getting errors when running the Features API section: if you [open the notebook in Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/13_loading_and_preprocessing_data.ipynb), it runs without any error (apart from some error messages during the installation of TFX at the very beginning, but these can be safely ignored for this notebook). Can you try checking that the library versions are identical?

**Comment by genemishchenko** [comment]
Yeah, I figured that you had to have the code somewhere, since it's published in the book :)
Good luck!
