### ISSUE TITLE
Preprocessing for Bach Chorales Dataset

### ISSUE THREAD

**Issue by SamNadjari** [ageron/handson-ml2#82]
I'm trying to preprocess the Bach chorales dataset to fit an RNN to it. The files are downloaded to my directory in 3 folders (train, valid, and test), each containing a number of csv files with a time series. How can I build a time series dataset from these files? How can I separate the last time step in each time series to use as the target values?

**Comment by voltum** [comment]
Hi Aurélien! I also have a question regarding this dataset: maybe you know how can it be played? I tried to google various online piano rolls and midi players (sort of), but none of them plays the music by the index of the note of the piano. I also searched for papers where this dataset is used, but looks like they just evaluate the accuracy of the result and do not play what was generated. Thanks in advance!

**Comment by ageron** [comment]
Hi @SamNadjari and @voltum ,

Sorry for the late response. I uploaded the solution to the exercise, in case you still want to take a look. 
In fact, I had fun generating some chorales, like [these](https://soundcloud.com/aurelien-geron/sets/bach-back-to-back). One of them is a real Bach chorale, can you find out which one?

@SamNadjari, there are many ways to preprocess the data. What I did is to convert the chords into arpegios, so for example [[1,2,3,4],[5,6,7,8]] is converted into [1,2,3,4,5,6,7,8]. This simplifies everything, in particular predicting the next chord is just a matter of predicting the next 4 notes, one at a time. For example [1,2,3,4,5,6,7,8]=>9, then [1,2,3,4,5,6,7,8,9]=>10, then [1,2,3,4,5,6,7,8,9,10]=>11, then [1,2,3,4,5,6,7,8,9,10,11]=>12, and finally you can convert the arpegios back into chords: [[1,2,3,4],[5,6,7,8],[9,10,11,12]].

@voltum, to play these notes, the simplest option is probably to generate a MIDI file, I believe there are some easy-to-use libraries for this, but that's not what I did. Just for fun I decided to synthesize the sound waves directly. :) The standard pitch A on the 4th octave is 440Hz, so if you generate a sound wave with that frequency, you will hear that note. It corresponds to note number 69 in the file (the notes start at C on "octave -1", then there are 12 semi-tones per octave, so C0 is number 12, C1 is number 24 and so on up to C4 which is number 60, and A4 which is number 69). Let's call r the frequency ratio between one note and the next (going up one semi-tone). Since the frequency doubles when you go up one octave, then r^12 must be equal to 2. So r=2^(1/12). All of this gives us the equation to find the frequency of a note given its index:

frequency = 440 * 2**((note - 69)/12)

You can check out the [code in the notebook](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/15_processing_sequences_using_rnns_and_cnns.ipynb). You just need to run the very first cell, then jump down to exercise 10 near the bottom of the notebook.

Hope this helps!
