### ISSUE TITLE
Chapter 11: Batch Normalization. Wrong equation?

### ISSUE THREAD

**Issue by RalfSchmidtner** [ageron/handson-ml2#88]
If <img src="https://render.githubusercontent.com/render/math?math=x^{(i)}"> is a vector and <img src="https://render.githubusercontent.com/render/math?math=\mu_B = \frac{1}{m_B}\sum\nolimits_{i=1}^{m_B}x^{(i)}">, than  <img src="https://render.githubusercontent.com/render/math?math=\mu_B"> is a scalar and not a vector. 

However the book states that <img src="https://render.githubusercontent.com/render/math?math=\mu_B"> is "the vector of input means".

How about writing this?

<img src="https://render.githubusercontent.com/render/math?math=\mu_B^{(j)} = \frac{1}{m_B}\sum\nolimits_{j=1}^{m_B}x^{(j)}"> where <img src="https://render.githubusercontent.com/render/math?math=n"> is the number of features and <img src="https://render.githubusercontent.com/render/math?math=j"> indicates the <img src="https://render.githubusercontent.com/render/math?math=j">-th feature. Note that I used <img src="https://render.githubusercontent.com/render/math?math=j"> as the index to refer to features, since the book uses <img src="https://render.githubusercontent.com/render/math?math=i"> in the third formula of the batch normalization procedure to refer to the <img src="https://render.githubusercontent.com/render/math?math=i">-th instance.

Same argument is valid for the definition of <img src="https://render.githubusercontent.com/render/math?math=\sigma_B^2">

**Comment by ageron** [comment]
Hi @RalfSchmidtner ,

Thanks for your question. When you compute the mean of a bunch of vectors of length _n_, the result is another vector of length _n_. For example, the mean of [1, 2, 3] and [7, 4, 11] is [4, 3, 7], not a scalar:

```python
>>> 1/2 * (np.array([1,2,3]) + np.array([7, 4, 11]))
array([4., 3., 7.])
```

If <img src="https://render.githubusercontent.com/render/math?math=\bf{x}^{(i)}"> is a vector of length _n_ (assuming there are _n_ features), then <img src="https://render.githubusercontent.com/render/math?math=\bf{\mu_B} = \frac{1}{m_B}\sum\nolimits_{i=1}^{m_B}\bf{x}^{(i)}"> returns a vector of length _n_. In short, <img src="https://render.githubusercontent.com/render/math?math=\bf{\mu_B}"> is just the mean of all the input vectors in the training batch.

So the equations in the book are correct, I believe.

Your proposed equation attempts to consider each feature individually (the equations in the book do the same computations in a vectorized way), but the indices are not quite right. The equation should sum over the instances in the batch, so the sum should be over _i_, not _j_.  Moreover, instead of <img src="https://render.githubusercontent.com/render/math?math=x^{(j)}"> it should be <img src="https://render.githubusercontent.com/render/math?math=x^{(i)}_j">, as we would consider the _j_-th feature of the _i_-th instance.

In the book, I use the superscript indices to index instances in a batch or in a dataset, whereas I use subscript indices to index features. So using this convention, if we wanted to consider each feature mean individually, then we would need to write something like this:

<img src="https://render.githubusercontent.com/render/math?math=\mu_{Bj} = \frac{1}{m_B}\sum\nolimits_{i=1}^{m_B}{x^{(i)}_j}">

I hope this helps,
Aurélien

**Comment by RalfSchmidtner** [comment]
It helped. The answer was as excellent as the book, thank you very much.
